---
- name: Install
  host: all
  become: yes
  task:
    
    - name: update repository index
      apt: 
        update_cache: yes

    - name: install python3-pip3 package
       apt:
         name:python3
       state: present

    - name: install python3-pip3 package
       apt:
         name:pip3
       state: present


    - name: use pip3 as default pip
      pip:
        executable: pip3

    - name: install Java
       apt:
         name: opejdk-11-jdk
       state: present


    - name: motd
      copy:
        content: "{{motd_text | deault('Ansible Manage node by Sarcauga')}}"
        dest: /etc/motd

    - name: user
       user:
         name:"{{'Sarcauga'}}"
       state: present



